export const COMPONENT_ICON_OPTIONS = [
  { value: 'account-circle', label: 'Account circle' },
  { value: 'arrow-right', label: 'Arrow right' },
  { value: 'baby', label: 'Baby' },
  { value: 'bullet-list', label: 'Bullet list' },
  { value: 'check', label: 'Check' },
  { value: 'community', label: 'Community' },
  { value: 'edit', label: 'Edit' },
  { value: 'family', label: 'Family' },
  { value: 'friends', label: 'Friends' },
  { value: 'github-cat', label: 'GitHub cat' },
  { value: 'github', label: 'GitHub' },
  { value: 'heart', label: 'Heart' },
  { value: 'house', label: 'House' },
  { value: 'info-round', label: 'Info round' },
  { value: 'languages', label: 'Languages' },
  { value: 'lightbulb', label: 'Lightbulb' },
  { value: 'lock', label: 'Lock' },
  { value: 'mail', label: 'Mail' },
  { value: 'memory-book', label: 'Memory book' },
  { value: 'minus', label: 'Minus' },
  { value: 'notes', label: 'Notes' },
  { value: 'open-star', label: 'Open star' },
  { value: 'photo', label: 'Photo' },
  { value: 'plus', label: 'Plus' },
  { value: 'question-round', label: 'Question round' },
  { value: 'redirect', label: 'Redirect' },
  { value: 'rotate-left', label: 'Rotate left' },
  { value: 'search', label: 'Search' },
  { value: 'shake-hands', label: 'Shake hands' },
  { value: 'star', label: 'Star' },
  { value: 'trash', label: 'Trash' },
  { value: 'two-persons', label: 'Two persons' },
  { value: 'video', label: 'Video' },
  { value: 'world', label: 'World' },
] as const

export type ComponentIconKey = (typeof COMPONENT_ICON_OPTIONS)[number]['value']
