/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    users: User;
    media: Media;
    memories: Memory;
    'open-when-messages': OpenWhenMessage;
    'loved-ones': LovedOne;
    'loved-one-groups': LovedOneGroup;
    'legacy-deliveries': LegacyDelivery;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    memories: MemoriesSelect<false> | MemoriesSelect<true>;
    'open-when-messages': OpenWhenMessagesSelect<false> | OpenWhenMessagesSelect<true>;
    'loved-ones': LovedOnesSelect<false> | LovedOnesSelect<true>;
    'loved-one-groups': LovedOneGroupsSelect<false> | LovedOneGroupsSelect<true>;
    'legacy-deliveries': LegacyDeliveriesSelect<false> | LegacyDeliveriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'nl') | ('en' | 'nl')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'nl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  profileImageUrl?: string | null;
  profileImage?: (number | null) | Media;
  enableLegacyProtection?: boolean | null;
  /**
   * The account owner asked to enable legacy protection, but selected trusted contacts still need to accept their invite.
   */
  legacyProtectionPendingEnable?: boolean | null;
  legacyProtectionContacts?: (number | LovedOne)[] | null;
  legacyCheckInMode?: ('user' | 'trusted') | null;
  legacyCheckInStage?: ('none' | 'user-first' | 'user-reminder' | 'trusted-pending') | null;
  legacyNextCheckInAt?: string | null;
  legacyCheckInSentAt?: string | null;
  legacyCheckInDueAt?: string | null;
  legacyCheckInTokenHash?: string | null;
  legacyTrustedContactTokenHash?: string | null;
  legacyLastConfirmedAt?: string | null;
  legacyLastTrustedResponseAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  posterUrl?: string | null;
  posterEncryptionMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isEncrypted?: boolean | null;
  encryptionMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ownerUser?: (number | null) | User;
  ownerAdmin?: (number | null) | Admin;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loved-ones".
 */
export interface LovedOne {
  id: number;
  fullName: string;
  nickname?: string | null;
  email: string;
  relationship: string;
  /**
   * Optional personal note for this loved one. Leave blank to use the shared default note.
   */
  customNote?: string | null;
  customNoteCiphertext?: string | null;
  customNoteEncryptionMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  groups: (number | LovedOneGroup)[];
  user: number | User;
  trustedContactInviteStatus?: ('none' | 'pending' | 'accepted') | null;
  trustedContactInviteTokenHash?: string | null;
  trustedContactInviteSentAt?: string | null;
  trustedContactInviteAcceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loved-one-groups".
 */
export interface LovedOneGroup {
  id: number;
  name: string;
  isDefault?: boolean | null;
  defaultKey?: string | null;
  iconKey?: string | null;
  colorKey?: string | null;
  user: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memories".
 */
export interface Memory {
  id: number;
  title: string;
  titleCiphertext?: string | null;
  titleEncryptionMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The date this memory is about. Payload automatically stores createdAt separately.
   */
  memoryDate: string;
  owner: number | User;
  keyCiphertext?: string | null;
  keyEncryptionMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Select one or more groups to link this memory to.
   */
  groups?: (number | LovedOneGroup)[] | null;
  /**
   * Select one or more loved ones to link this memory to.
   */
  lovedOnes?: (number | LovedOne)[] | null;
  content: {
    type: 'note' | 'image' | 'video';
    note?: string | null;
    noteCiphertext?: string | null;
    noteEncryptionMetadata?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    media?: (number | null) | Media;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open-when-messages".
 */
export interface OpenWhenMessage {
  id: number;
  title: string;
  titleCiphertext?: string | null;
  titleEncryptionMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  openWhenText: string;
  openWhenTextCiphertext?: string | null;
  openWhenTextEncryptionMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  message: string;
  messageCiphertext?: string | null;
  messageEncryptionMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  iconKey?: string | null;
  colorKey?: string | null;
  owner: number | User;
  /**
   * Select one or more loved ones who this message is for.
   */
  lovedOnes: (number | LovedOne)[];
  attachments?: (number | Media)[] | null;
  /**
   * Reminder date. This is not a send date unless allowSendWhileActive is enabled.
   */
  triggerDate?: string | null;
  /**
   * If enabled, this message can be shared with the selected loved one(s) on the chosen date, even while the vault is still active.
   */
  allowSendWhileActive?: boolean | null;
  dateNotificationSent?: string | null;
  sentAt?: string | null;
  status: 'draft' | 'active' | 'date_reached' | 'sent' | 'released';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legacy-deliveries".
 */
export interface LegacyDelivery {
  id: number;
  status: 'active' | 'revoked';
  tokenHash: string;
  accessPasswordHash?: string | null;
  recipientName: string;
  recipientEmail?: string | null;
  deliveredAt: string;
  owner: number | User;
  lovedOne: number | LovedOne;
  /**
   * Optional app account that claimed this recipient delivery.
   */
  recipientUser?: (number | null) | User;
  memories: (number | Memory)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'memories';
        value: number | Memory;
      } | null)
    | ({
        relationTo: 'open-when-messages';
        value: number | OpenWhenMessage;
      } | null)
    | ({
        relationTo: 'loved-ones';
        value: number | LovedOne;
      } | null)
    | ({
        relationTo: 'loved-one-groups';
        value: number | LovedOneGroup;
      } | null)
    | ({
        relationTo: 'legacy-deliveries';
        value: number | LegacyDelivery;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  profileImageUrl?: T;
  profileImage?: T;
  enableLegacyProtection?: T;
  legacyProtectionPendingEnable?: T;
  legacyProtectionContacts?: T;
  legacyCheckInMode?: T;
  legacyCheckInStage?: T;
  legacyNextCheckInAt?: T;
  legacyCheckInSentAt?: T;
  legacyCheckInDueAt?: T;
  legacyCheckInTokenHash?: T;
  legacyTrustedContactTokenHash?: T;
  legacyLastConfirmedAt?: T;
  legacyLastTrustedResponseAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  posterUrl?: T;
  posterEncryptionMetadata?: T;
  isEncrypted?: T;
  encryptionMetadata?: T;
  ownerUser?: T;
  ownerAdmin?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memories_select".
 */
export interface MemoriesSelect<T extends boolean = true> {
  title?: T;
  titleCiphertext?: T;
  titleEncryptionMetadata?: T;
  memoryDate?: T;
  owner?: T;
  keyCiphertext?: T;
  keyEncryptionMetadata?: T;
  groups?: T;
  lovedOnes?: T;
  content?:
    | T
    | {
        type?: T;
        note?: T;
        noteCiphertext?: T;
        noteEncryptionMetadata?: T;
        media?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open-when-messages_select".
 */
export interface OpenWhenMessagesSelect<T extends boolean = true> {
  title?: T;
  titleCiphertext?: T;
  titleEncryptionMetadata?: T;
  openWhenText?: T;
  openWhenTextCiphertext?: T;
  openWhenTextEncryptionMetadata?: T;
  message?: T;
  messageCiphertext?: T;
  messageEncryptionMetadata?: T;
  iconKey?: T;
  colorKey?: T;
  owner?: T;
  lovedOnes?: T;
  attachments?: T;
  triggerDate?: T;
  allowSendWhileActive?: T;
  dateNotificationSent?: T;
  sentAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loved-ones_select".
 */
export interface LovedOnesSelect<T extends boolean = true> {
  fullName?: T;
  nickname?: T;
  email?: T;
  relationship?: T;
  customNote?: T;
  customNoteCiphertext?: T;
  customNoteEncryptionMetadata?: T;
  groups?: T;
  user?: T;
  trustedContactInviteStatus?: T;
  trustedContactInviteTokenHash?: T;
  trustedContactInviteSentAt?: T;
  trustedContactInviteAcceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loved-one-groups_select".
 */
export interface LovedOneGroupsSelect<T extends boolean = true> {
  name?: T;
  isDefault?: T;
  defaultKey?: T;
  iconKey?: T;
  colorKey?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legacy-deliveries_select".
 */
export interface LegacyDeliveriesSelect<T extends boolean = true> {
  status?: T;
  tokenHash?: T;
  accessPasswordHash?: T;
  recipientName?: T;
  recipientEmail?: T;
  deliveredAt?: T;
  owner?: T;
  lovedOne?: T;
  recipientUser?: T;
  memories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}